ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS line_user_id
    TEXT NOT NULL DEFAULT '';

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS line_display_name
    TEXT NOT NULL DEFAULT '';

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS total_amount
    INTEGER NOT NULL DEFAULT 0;